args <- commandArgs(trailingOnly = TRUE)
get_arg <- function(flag, default = NULL) {
  hit <- which(args == flag)
  if (length(hit) == 0 || hit == length(args)) return(default)
  args[[hit + 1]]
}
rds_path <- get_arg("--rds")
config_path <- get_arg("--config", "config/smoc1.yml")
out_dir <- get_arg("--out", "results/reference")
if (is.null(rds_path)) stop("Usage: Rscript R/02_reference_projection.R --rds integrated.rds [--config file] [--out dir]")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
suppressPackageStartupMessages({ library(Seurat); library(yaml) })
obj <- readRDS(rds_path)
cfg <- yaml::read_yaml(config_path)
markers <- intersect(names(cfg$alpha_markers), rownames(obj))
if (length(markers) < 2) stop("At least two alpha markers are needed.")
data_mat <- GetAssayData(obj, assay = DefaultAssay(obj), slot = "data")
obj$alpha_marker_score <- Matrix::colMeans(data_mat[markers, , drop = FALSE])
obj$cell_state <- as.character(Idents(obj))
alpha_like <- obj$alpha_marker_score > stats::quantile(obj$alpha_marker_score, 0.65, na.rm = TRUE)
obj$cell_state[alpha_like] <- paste0("alpha_cluster_", obj$seurat_clusters[alpha_like])
obj$cell_state[!alpha_like] <- paste0("other_cluster_", obj$seurat_clusters[!alpha_like])
umap <- Embeddings(obj, "umap")
velocity_metadata <- data.frame(cell_id = rownames(umap), UMAP_1 = umap[, 1], UMAP_2 = umap[, 2], cell_state = obj$cell_state[rownames(umap)], donor_id = obj$donor_id[rownames(umap)], condition = obj$condition[rownames(umap)], stringsAsFactors = FALSE)
write.table(velocity_metadata, file.path(out_dir, "velocity_metadata.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(obj[[]], file.path(out_dir, "reference_metadata.tsv"), sep = "\t", quote = FALSE, row.names = TRUE)
saveRDS(obj, file.path(out_dir, "reference.rds"))
message("Review cell_state labels before velocity.")

